### ISSUE TITLE
responsive menu

### ISSUE THREAD

**Issue by sarahball** [cjkoepke/starter-theme#3]
The responsive menu is active by default, and there are no toggle buttons to open and close it.

**Comment by cjkoepke** [comment]
Sorry, I need more information than this. Please provide a screenshot and what your current menu setup is like.

**Comment by sarahball** [comment]
Hey Calvin, I ended up switching to a different menu because I couldn't get it working, even on a fresh WP installation. Sorry I didn't get any screenshots.

**Comment by cjkoepke** [comment]
@sarahball Sounds good. Just for reference, the menu is now open source with documentation, in case you want to try again: https://github.com/copyblogger/responsive-menus
